- icon: icon-user-md
  title: Social support
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?

- icon: icon-diamond
  title: Psychological support
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?

- icon: icon-flask
  title: Spiritual empowerment
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit.

- icon: icon-globe
  title: Education
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?

- icon: icon-globe
  title: Life Skills
  description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam minima, itaque molestiae ut ratione unde?
